### ISSUE TITLE
Caching issues

### ISSUE THREAD

**Issue by antonioned** [medyagh/setup-minikube#102]
I am running this to set up a minikube in my gh actions and whenever I push new code the cluster runs with the following message at the end

```
isoError: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.
```

I am trying to see if I am doing something wrong but from what I understand out of this [issue](https://github.com/medyagh/setup-minikube/issues/16) and this [PR](https://github.com/medyagh/setup-minikube/pull/46), I don't need to add any additional caching in my pipeline?

**Comment by spowelljr** [comment]
Hi @antonioned, there's nothing actually wrong, but I do understand where the confusing is coming from.

If you start minikube with Docker it downloads a kicbase image and if you start minikube using a VM it downloads an ISO image, it them tries to cache both images but you'll only have one. So it seems you're using Docker so a kicbase image is being downloaded but an ISO isn't, which is expected, but then it tries to cache the ISO image as well and fails so you see the error message that you pointed out.

We can easily fix this by checking for the existence of the folder before trying to cache.

**Comment by antonioned** [comment]
Thanks for the quick turnaround @spowelljr

**Comment by CpuID** [comment]
I suspect this warning is related to the changes made for this issue...?

```
Cache hit for: preloaded-tarball-v1.35.0-x64-v1.25.0-docker
Warning: Cache not found for keys: iso-v1.35.0-x64
Cache hit for: kic-v1.35.0-x64
```

Would it be worth suppressing the `Warning: Cache not found` in these situations...?
