### ISSUE TITLE
get the latest version of minikube from releases

### ISSUE THREAD

**Issue by georgettica** [medyagh/setup-minikube#15]
https://github.com/kubernetes/minikube/releases

https://github.com/medyagh/setup-minikube/blob/5a9a7104d7322fa40424de8855c84685e89cefd7/src/main.ts#L7

**Comment by georgettica** [comment]
you are currently hard-coded on 1.10 :(

**Comment by medyagh** [comment]
thanks for the issue, I just merged the PR that allows configing it
