### ISSUE TITLE
404 not found when using the minikube version to `stable`

### ISSUE THREAD

**Issue by georgettica** [medyagh/setup-minikube#23]
see PR https://github.com/change-metrics/monocle/pull/795

this was also checked with `medyagh/setup-minikube@v0.0.7`

that fails on https://github.com/change-metrics/monocle/runs/4616467871?check_suite_focus=true
```
Error: Unexpected HTTP response: 404
```

not sure how to debug this

**Comment by georgettica** [comment]
I was excited of the new `kubernetes-version` and `minikube-version`

**Comment by medyagh** [comment]
hm...how about medyagh/setup-minikube@latest ? does that work ?

**Comment by georgettica** [comment]
I wanted to express a user concern now that I solved it.

The issue was one variable needed the string `stable` and the other `latest`

And I used the wrong one.
Could you make sure that if the wrong string is entered the actions response will direct the user to the correct string / note it wasn't able to pull using the version noted?

Thanks in advance and I really appreciate the time you invested in debugging this issue

**Comment by medyagh** [comment]
that sounds resonable we could accept "stable" as a synonym for "latest"

**Comment by spowelljr** [comment]
Implementing this

**Comment by spowelljr** [comment]
https://github.com/medyagh/setup-minikube/pull/27

**Comment by medyagh** [comment]
@georgettica now stable should work ! plz give it a try

**Comment by georgettica** [comment]
I'll try Sunday
Thanks for working on this!
