### ISSUE TITLE
setup-minikube: Cache Upload Failed Because File read failed with EBADF

### ISSUE THREAD

**Issue by MubashirUsman** [medyagh/setup-minikube#235]
Hi, I am using a self hosted Github Runner on my local MacOS (version 12.3.1) and I receive this error during running of `medyagh/setup-minikube@master`: 
```
Failed to save: uploadChunk (start: 33554432, end: 67108863) failed: Cache service responded with 503
/Users/mubahsirusman/Documents/k8slocal/actions-runner/_work/_actions/medyagh/setup-minikube/master/dist/index.js:827
throw new Error(`Cache upload failed because file read failed with ${error.message}`);
Error: Cache upload failed because file read failed with EBADF: bad file descriptor, read

at ReadStream.<anonymous> (/Users/mubahsirusman/Documents/k8slocal/actions-runner/_work/_actions/medyagh/setup-minikube/master/dist/index.js:827:31)
```
Sometimes the job runs successfully, can someone share some insight on what exactly is it doing and what is causing this error.

**Comment by spowelljr** [comment]
I'm not exactly sure what is causing this, but you can disable the usage of cache (which should resolve your issue) by setting the following in your GitHub Actions workflow file:
```
- uses: medyagh/setup-minikube@master
  with:
    cache: false
```
