### ISSUE TITLE
Error setting up on self hosted runner

### ISSUE THREAD

**Issue by agunapal** [medyagh/setup-minikube#301]
I get this error when trying to setup on a self hosted runner

```
Run medyagh/setup-minikube@latest
Error: EACCES: permission denied, mkdir '/home/runner'
```

I guess thats expected since there is no user called `runner`.

How do I get around this?

**Comment by spowelljr** [comment]
Hi @agunapal, the issue is we actually have `/home/runner` hardcoded, I'll update this to use `os.homedir()`

https://github.com/medyagh/setup-minikube/blob/9ed194ee345beecad406ec1b59b177509f00dcf2/src/download.ts#L55
